version: "3.8"
services:
  postgres_docker:
    image: "postgres:13"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=data_engineer
      - POSTGRES_PASSWORD=etl_project
      - POSTGRES_DB=etl_project
